-- شغّل الكود ده كامل في Supabase: SQL Editor > New query > الصق > Run

-- 1) عمود تاريخ التسليم — منه بتتحسب مدة الاسترجاع (14 يوم)
alter table orders add column if not exists delivered_at timestamptz;

-- الطلبات القديمة المسلّمة: بنحطلها تاريخ الطلب كتقدير (لصالح العميل)
update orders
set delivered_at = created_at
where status = 'delivered' and delivered_at is null;

-- 2) جدول طلبات الاسترجاع والاستبدال
create table if not exists return_requests (
  id bigint generated by default as identity primary key,
  order_id text not null,
  customer_name text,
  customer_phone text,
  kind text not null,              -- 'return' استرجاع  |  'exchange' استبدال
  item_name text,                  -- اسم القطعة زي ما هي في الطلب
  item_qty integer default 1,
  wanted_size text,                -- المقاس المطلوب (للاستبدال)
  wanted_color text,               -- اللون المطلوب (للاستبدال)
  reason text,
  note text,
  status text default 'new',       -- new | approved | rejected | done
  admin_note text,
  created_at timestamptz default now()
);

alter table return_requests enable row level security;

create index if not exists return_requests_order_idx on return_requests(order_id);
