-- ⚠️ لو شغّلت جزء الهيرو قبل كده، شغّل الجزء الجديد بس (تحت الخط)

-- ===================== (شغّلته قبل كده) =====================
create table if not exists hero_slides (
  id bigint generated by default as identity primary key,
  image_url text,
  title text,
  description text,
  cta_label text,
  cta_link text,
  badge text,
  sort_order integer,
  published boolean default true,
  created_at timestamptz default now()
);

alter table hero_slides enable row level security;

-- ===================== الجزء الجديد =====================
-- جدول إعدادات عامة للموقع (بنستخدمه دلوقتي لزرار تشغيل/إلغاء السلايدر كله)
create table if not exists site_settings (
  key text primary key,
  value text
);

alter table site_settings enable row level security;

insert into site_settings (key, value)
values ('hero_enabled', 'true')
on conflict (key) do nothing;
