-- جدول حسابات العملاء: رقم موبايل + كلمة سر مشفّرة + بيانات شخصية اختيارية
create table if not exists customers (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  password_hash text not null,
  name text,
  city text,
  address text,
  created_at timestamptz default now()
);
