-- شغّل الكود ده في Supabase SQL Editor

create table if not exists coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  type text not null default 'percent',   -- 'percent' أو 'fixed'
  value numeric not null,                 -- النسبة أو المبلغ
  expires_at date,                        -- تاريخ الانتهاء (اختياري)
  max_uses integer,                       -- أقصى عدد مرات استخدام (اختياري)
  uses integer not null default 0,        -- عدد مرات الاستخدام الفعلي
  min_total numeric,                      -- حد أدنى لقيمة الطلب (اختياري)
  min_items integer,                      -- حد أدنى لعدد القطع (اختياري)
  active boolean not null default true,
  created_at timestamptz default now()
);

alter table coupons enable row level security;

-- حقول الكوبون في الطلب
alter table orders add column if not exists coupon_code text;
alter table orders add column if not exists discount numeric default 0;
alter table orders add column if not exists subtotal numeric;
