-- شغّل الكود ده كامل في Supabase: SQL Editor > New query > الصق كل ده > Run

create table if not exists products (
  id bigint generated by default as identity primary key,
  cat text not null,
  icon text not null,
  name text not null,
  description text not null,
  price numeric not null
);

create table if not exists orders (
  id text primary key,
  date text,
  items jsonb not null,
  total numeric not null,
  name text,
  phone text,
  city text,
  address text,
  pay text,
  created_at timestamptz default now()
);

-- بيانات ابتدائية (نفس منتجات النسخة التجريبية)
insert into products (cat, icon, name, description, price) values
('men','shirt','قميص كتان كلاسيك','قصة مريحة، قطن مصري 100%، مناسب للإطلالات اليومية والرسمية الخفيفة.',189),
('men','jacket','جاكيت جينز أزرق','خامة دنيم متينة بتصميم كلاسيكي يدوم لسنوات مع كل غسلة.',295),
('men','pants','بنطلون قماش رمادي','قصة ضيقة عصرية، قماش مرن يمنحك حرية حركة كاملة.',210),
('women','dress','فستان صيفي مزهّر','شيفون خفيف بتهوية ممتازة، مثالي لأيام الصيف الحارة.',249),
('women','shirt','بلوزة حرير وردية','لمسة ناعمة وأنيقة، مناسبة للعمل والمناسبات الخفيفة.',175),
('women','dress','تنورة بليه صفراء','طول متوسط بخصر مطاطي مريح يناسب مختلف المقاسات.',159),
('women','shirt','بلوزة أكمام واسعة','قماش قطن مطاط بقصة عصرية سهلة التنسيق.',165);

-- تفعيل الحماية (RLS) ومنع أي وصول مباشر من المتصفح
-- (الموقع بيوصل لقاعدة البيانات فقط من خلال الخادم عن طريق الـ Service Role Key)
alter table products enable row level security;
alter table orders enable row level security;
